node {

  // job
  try {
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has failed!')
      sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";

    // send slack notification
    // slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
       slackSend (baseUrl: 'https://hooks.slack.com/services/', 
                 channel: '#jenkins-slack', 
                 color: '#439FE0', 
                  message: "Failed: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})",
                 teamDomain: 'devopsshahu', 
                 tokenCredentialId: 'slack_alerts')

    // throw the error
    throw e;
  }
}
